-- courtesy of Trusts addon by from20020516
trusts = T{
    [1]={id=896,japanese="シャントット",english="Shantotto",name="Shantotto",models=3000, mjob="BLM"},
    [2]={id=897,japanese="ナジ",english="Naji",name="Naji",models=3001, mjob="WAR"},
    [3]={id=898,japanese="クピピ",english="Kupipi",name="Kupipi",models=3002, mjob="WHM"},
    [4]={id=899,japanese="エグセニミル",english="Excenmille",name="Excenmille",models=3003, mjob="PLD"},
    [5]={id=900,japanese="アヤメ",english="Ayame",name="Ayame",models=3004}, mjob="SAM",
    [6]={id=901,japanese="ナナー・ミーゴ",english="Nanaa Mihgo",name="NanaaMihgo",models=3005, mjob="THF"},
    [7]={id=902,japanese="クリルラ",english="Curilla",name="Curilla",models=3006, mjob="PLD"},
    [8]={id=903,japanese="フォルカー",english="Volker",name="Volker",models=3007, mjob="WAR"},
    [9]={id=904,japanese="アジドマルジド",english="Ajido-Marujido",name="Ajido-Marujido",models=3008, mjob="BLM"},
    [10]={id=905,japanese="トリオン",english="Trion",name="Trion",models=3009, mjob="PLD"},
    [11]={id=906,japanese="ザイド",english="Zeid",name="Zeid",models=3010, mjob="DRK"},
    [12]={id=907,japanese="ライオン",english="Lion",name="Lion",models=3011, mjob="THF"},
    [13]={id=908,japanese="テンゼン",english="Tenzen",name="Tenzen",models=3012, mjob="SAM"},
    [14]={id=909,japanese="ミリ・アリアポー",english="Mihli Aliapoh",name="MihliAliapoh",models=3013, mjob="WHM"},
    [15]={id=910,japanese="ヴァレンラール",english="Valaineral",name="Valaineral",models=3014, mjob="PLD"},
    [16]={id=911,japanese="ヨアヒム",english="Joachim",name="Joachim",models=3015, mjob="BRD"},
    [17]={id=912,japanese="ナジャ・サラヒム",english="Naja Salaheem",name="NajaSalaheem",models=3016, mjob="MNK"},
    [18]={id=913,japanese="プリッシュ",english="Prishe",name="Prishe",models=3017, mjob="MNK"},
    [19]={id=914,japanese="ウルミア",english="Ulmia",name="Ulmia",models=3018, mjob="BRD"},
    [20]={id=915,japanese="スカリーZ",english="Shikaree Z",name="ShikareeZ",models=3019, mjob="DRG"},
    [21]={id=916,japanese="チェルキキ",english="Cherukiki",name="Cherukiki",models=3020, mjob="WHM"},
    [22]={id=917,japanese="アイアンイーター",english="Iron Eater",name="IronEater",models=3021, mjob="WAR"},
    [23]={id=918,japanese="ゲッショー",english="Gessho",name="Gessho",models=3022, mjob="NIN"},
    [24]={id=919,japanese="ガダラル",english="Gadalar",name="Gadalar",models=3023, mjob="BLM"},
    [25]={id=920,japanese="ライニマード",english="Rainemard",name="Rainemard",models=3024, mjob="RDM"},
    [26]={id=921,japanese="イングリッド",english="Ingrid",name="Ingrid",models=3025, mjob="WHM"},
    [27]={id=922,japanese="レコ・ハボッカ",english="Lehko Habhoka",name="LehkoHabhoka",models=3026, mjob="THF"},
    [28]={id=923,japanese="ナシュメラ",english="Nashmeira",name="Nashmeira",models=3027, mjob="WHM"},
    [29]={id=924,japanese="ザザーグ",english="Zazarg",name="Zazarg",models=3028, mjob="MNK"},
    [30]={id=925,japanese="アヴゼン",english="Ovjang",name="Ovjang",models=3029, mjob="RDM"},
    [31]={id=926,japanese="メネジン",english="Mnejing",name="Mnejing",models=3030, mjob="PLD"},
    [32]={id=927,japanese="サクラ",english="Sakura",name="Sakura",models=3031, mjob="GEO"},
    [33]={id=928,japanese="ルザフ",english="Luzaf",name="Luzaf",models=3032, mjob="COR"},
    [34]={id=929,japanese="ナジュリス",english="Najelith",name="Najelith",models=3033, mjob="RNG"},
    [35]={id=930,japanese="アルド",english="Aldo",name="Aldo",models=3034, mjob="THF"},
    [36]={id=931,japanese="モーグリ",english="Moogle",name="Moogle",models=3035, mjob="GEO"},
    [37]={id=932,japanese="ファブリニクス",english="Fablinix",name="Fablinix",models=3036, mjob="RDM"},
    [38]={id=933,japanese="マート",english="Maat",name="Maat",models=3037, mjob="MNK"},
    [39]={id=934,japanese="D.シャントット",english="D. Shantotto",name="D.Shantotto",models=3038, mjob="BLM"},
    [40]={id=935,japanese="星の神子",english="Star Sibyl",name="StarSibyl",models=3039, mjob="GEO"},
    [41]={id=936,japanese="カラハバルハ",english="Karaha-Baruha",name="Karaha-Baruha",models=3040, mjob="WHM"},
    [42]={id=937,japanese="シド",english="Cid",name="Cid",models=3041, mjob="WAR"},
    [43]={id=938,japanese="ギルガメッシュ",english="Gilgamesh",name="Gilgamesh",models=3042, mjob="SAM"},
    [44]={id=939,japanese="アレヴァト",english="Areuhat",name="Areuhat",models=3043, mjob="WAR"},
    [45]={id=940,japanese="セミ・ラフィーナ",english="Semih Lafihna",name="SemihLafihna",models=3044, mjob="RNG"},
    [46]={id=941,japanese="エリヴィラ",english="Elivira",name="Elivira",models=3045, mjob="RNG"},
    [47]={id=942,japanese="ノユリ",english="Noillurie",name="Noillurie",models=3046, mjob="SAM"},
    [48]={id=943,japanese="ルー・マカラッカ",english="Lhu Mhakaracca",name="LhuMhakaracca",models=3047, mjob="BST"},
    [49]={id=944,japanese="フェリアスコフィン",english="Ferreous Coffin",name="FerreousCoffin",models=3048, mjob="WHM"},
    [50]={id=945,japanese="リリゼット",english="Lilisette",name="Lilisette",models=3049, mjob="DNC"},
    [51]={id=946,japanese="ミュモル",english="Mumor",name="Mumor",models=3050, mjob="DNC"},
    [52]={id=947,japanese="ウカ・トトゥリン",english="Uka Totlihn",name="UkaTotlihn",models=3051, mjob="DNC"},
    [53]={id=948,japanese="クララ",english="Klara",name="Klara",models=3053, mjob="WAR"},
    [54]={id=949,japanese="ロマー・ミーゴ",english="Romaa Mihgo",name="RomaaMihgo",models=3054, mjob="THF"},
    [55]={id=950,japanese="クイン・ハスデンナ",english="Kuyin Hathdenna",name="KuyinHathdenna",models=3055, mjob="GEO"},
    [56]={id=951,japanese="ラーアル",english="Rahal",name="Rahal",models=3056, mjob="PLD"},
    [57]={id=952,japanese="コルモル",english="Koru-Moru",name="Koru-Moru",models=3057, mjob="RDM"},
    [58]={id=953,japanese="ピエージェ(UC)",english="Pieuje (UC)",name="Pieuje",models=3058, mjob="WHM"},
    [59]={id=954,japanese="I.シールド(UC)",english="I. Shield (UC)",name="InvincibleShld",models=3060, mjob="WAR"},
    [60]={id=955,japanese="アプルル(UC)",english="Apururu (UC)",name="Apururu",models=3061, mjob="WHM"},
    [61]={id=956,japanese="ジャコ(UC)",english="Jakoh (UC)",name="JakohWahcondalo",models=3062, mjob="THF"},
    [62]={id=957,japanese="フラヴィリア(UC)",english="Flaviria (UC)",name="Flaviria",models=3059, mjob="DRG"},
    [63]={id=958,japanese="ウェイレア",english="Babban",name="Babban",models=3067, mjob="MNK"},
    [64]={id=959,japanese="アベンツィオ",english="Abenzio",name="Abenzio",models=3068, mjob="THF"},
    [65]={id=960,japanese="ルガジーン",english="Rughadjeen",name="Rughadjeen",models=3069, mjob="PLD"},
    [66]={id=961,japanese="クッキーチェブキー",english="Kukki-Chebukki",name="Kukki-Chebukki",models=3070, mjob="BLM"},
    [67]={id=962,japanese="マルグレート",english="Margret",name="Margret",models=3071, mjob="RNG"},
    [68]={id=963,japanese="チャチャルン",english="Chacharoon",name="Chacharoon",models=3072, mjob="THF"},
    [69]={id=964,japanese="レイ・ランガヴォ",english="Lhe Lhangavo",name="LheLhangavo",models=3073, mjob="MNK"},
    [70]={id=965,japanese="アシェラ",english="Arciela",name="Arciela",models=3074, mjob="RDM"},
    [71]={id=966,japanese="マヤコフ",english="Mayakov",name="Mayakov",models=3075, mjob="DNC"},
    [72]={id=967,japanese="クルタダ",english="Qultada",name="Qultada",models=3076, mjob="COR"},
    [73]={id=968,japanese="アーデルハイト",english="Adelheid",name="Adelheid",models=3077, mjob="SCH"},
    [74]={id=969,japanese="アムチュチュ",english="Amchuchu",name="Amchuchu",models=3078, mjob="RUN"},
    [75]={id=970,japanese="ブリジッド",english="Brygid",name="Brygid",models=3079, mjob="GEO"},
    [76]={id=971,japanese="ミルドリオン",english="Mildaurion",name="Mildaurion",models=3080, mjob="PLD"},
    [77]={id=972,japanese="ハルヴァー",english="Halver",name="Halver",models=3087, mjob="PLD"},
    [78]={id=973,japanese="ロンジェルツ",english="Rongelouts",name="Rongelouts",models=3088, mjob="WAR"},
    [79]={id=974,japanese="レオノアーヌ",english="Leonoyne",name="Leonoyne",models=3089, mjob="BLM"},
    [80]={id=975,japanese="マクシミリアン",english="Maximilian",name="Maximilian",models=3090, mjob="THF"},
    [81]={id=976,japanese="カイルパイル",english="Kayeel-Payeel",name="Kayeel-Payeel",models=3091, mjob="BLM"},
    [82]={id=977,japanese="ロベルアクベル",english="Robel-Akbel",name="Robel-Akbel",models=3092, mjob="BLM"},
    [83]={id=978,japanese="クポフリート",english="Kupofried",name="Kupofried",models=3093, mjob="GEO"},
    [84]={id=979,japanese="セルテウス",english="Selh\'teus",name="Selh\'teus",models=3094, mjob="PLD"},
    [85]={id=980,japanese="ヨランオラン(UC)",english="Yoran-Oran (UC)",name="Yoran-Oran",models=3095, mjob="WHM"},
    [86]={id=981,japanese="シルヴィ(UC)",english="Sylvie (UC)",name="Sylvie",models=3096, mjob="GEO"},
    [87]={id=982,japanese="アブクーバ",english="Abquhbah",name="Abquhbah",models=3098, mjob="WAR"},
    [88]={id=983,japanese="バラモア",english="Balamor",name="Balamor",models=3099, mjob="DRK"},
    [89]={id=984,japanese="オーグスト",english="August",name="August",models=3100, mjob="PLD"},
    [90]={id=985,japanese="ロスレーシャ",english="Rosulatia",name="Rosulatia",models=3101, mjob="BLM"},
    [91]={id=986,japanese="テオドール",english="Teodor",name="Teodor",models=3103, mjob="BLM"},
    [92]={id=987,japanese="ウルゴア",english="Ullegore",name="Ullegore",models=3105, mjob="BLM"},
    [93]={id=988,japanese="マッキーチェブキー",english="Makki-Chebukki",name="Makki-Chebukki",models=3106, mjob="RNG"},
    [94]={id=989,japanese="キング・オブ・ハーツ",english="King of Hearts",name="KingOfHearts",models=3107, mjob="RDM"},
    [95]={id=990,japanese="モリマー",english="Morimar",name="Morimar",models=3108, mjob="BST"},
    [96]={id=991,japanese="ダラクァルン",english="Darrcuiln",name="Darrcuiln",models=3109, mjob="WAR"},
    [97]={id=992,japanese="アークHM",english="AAHM",name="ArkHM",models=3113, mjob="NIN"},
    [98]={id=993,japanese="アークEV",english="AAEV",name="ArkEV",models=3114, mjob="PLD"},
    [99]={id=994,japanese="アークMR",english="AAMR",name="ArkMR",models=3115, mjob="BST"},
    [100]={id=995,japanese="アークTT",english="AATT",name="ArkTT",models=3116, mjob="BLM"},
    [101]={id=996,japanese="アークGK",english="AAGK",name="ArkGK",models=3117, mjob="SAM"},
    [102]={id=997,japanese="イロハ",english="Iroha",name="Iroha",models=3111, mjob="SAM"},
    [103]={id=998,japanese="ユグナス",english="Ygnas",name="Ygnas",models=3118, mjob="WHM"},
    [104]={id=1004,japanese="エグセニミルII",english="Excenmille [S]",name="Excenmille",models=3052, mjob="PLD"},
    [105]={id=1005,japanese="アヤメ(UC)",english="Ayame (UC)",name="Ayame",models=3063, mjob="SAM"},
    [106]={id=1006,japanese="マート(UC)",english="Maat (UC)",name="Maat",models=3064, mjob="MNK"}, --expected models
    [107]={id=1007,japanese="アルド(UC)",english="Aldo (UC)",name="Aldo",models=3065, mjob="THF"}, --expected models
    [108]={id=1008,japanese="ナジャ(UC)",english="Naja (UC)",name="NajaSalaheem",models=3066, mjob="MNK"},
    [109]={id=1009,japanese="ライオンII",english="Lion II",name="Lion",models=3081, mjob="THF"},
    [110]={id=1010,japanese="ザイドII",english="Zeid II",name="Zeid",models=3086, mjob="DRK"},
    [111]={id=1011,japanese="プリッシュII",english="Prishe II",name="Prishe",models=3082, mjob="MNK"},
    [112]={id=1012,japanese="ナシュメラII",english="Nashmeira II",name="Nashmeira",models=3083, mjob="WHM"},
    [113]={id=1013,japanese="リリゼットII",english="Lilisette II",name="Lilisette",models=3084, mjob="DNC"},
    [114]={id=1014,japanese="テンゼンII",english="Tenzen II",name="Tenzen",models=3097, mjob="SAM"},
    [115]={id=1015,japanese="ミュモルII",english="Mumor II",name="Mumor",models=3104, mjob="DNC"},
    [116]={id=1016,japanese="イングリッドII",english="Ingrid II",name="Ingrid",models=3102, mjob="WHM"},
    [117]={id=1017,japanese="アシェラII",english="Arciela II",name="Arciela",models=3085, mjob="RDM"},
    [118]={id=1018,japanese="イロハII",english="Iroha II",name="Iroha",models=3112, mjob="SAM"},
    [119]={id=1019,japanese="シャントットII",english="Shantotto II",name="Shantotto",models=3110, mjob="BLM"},
--  [120]={id=1003,japanese="コーネリア",english="Cornelia",name="Cornelia",models=3119, mjob="WHM"}, --goodbye, my love
    [121]={id=999,japanese="モンブロー",english="Monberaux",name="Monberaux",models=3120, mjob="PLD"},
    [122]={id=1003,japanese="マツイP",english="Matsui-P",name="Matsui-P",models=3121, mjob="NIN"},
}
